### PR TITLE
Add support for vectors

### PR DESCRIPTION
**Pull request by dylex**
Just like list. Should work with any version of the vector package.

### CODE REVIEW

**Comment by dylex** [comment]
Also added some Eq, Ord instances. Can make a separate PR if you'd rather.

**Comment by dzhus** [comment]
Looks fine to me. Out of curiosity, do you have a specific use case for this or doing it just for exercise? I didn't originally include any Vector support as I saw no use for string-like operations on vectors (and for type-encoded vector lengths one might use something like `linear` package).

**Comment by dylex** [comment]
So, I do have a use case, but it's true that sext isn't exactly right for it. What I want is simple enough I may just do it myself, but for now sext was almost right, and there seemed no reason not to have Vectors.

Basically, I'm generating haskell (types) from a pre-defined DSL (RPC XDR) which has both fixed- and bounded-length bytestrings and arbitrary arrays. The most common case is bounded arrays with huge bounds, so I don't want to bog down the users with something strongly-typed like `fixed-length` or lots of dependencies. Really I just want to encode the length (or bound) in the type and provide convienent ways of (dynamically) asserting (checking, trimming, padding) the bound. The `Sext` class provided pretty much this (`length`, `take`, `replicate`, `append`), so I figured I'd try it to start.

**Comment by dzhus** [comment]
Fair enough. Thank you for your contribution, the patch has been included in sext-0.1.2.

**Pull request merged**
